function videoEnd(){var background=$("#background").get(0);background.play();console.log("Intro has ended");$("#intro").fadeOut(200);$("#black").fadeOut(1000);document.getElementById("music").play();$("#bar").css({transform:"translate(0, -50%)",opacity:'1'})
setTimeout(function(){$("#bar").css("height","25vw");},3000);setTimeout(function(){$("#eve").css({transform:"translateX(0)",opacity:"1"});},4000)
setTimeout(function(){$("#mainBox").css({height:"33vw",opacity:"1"});$("#nav").css({height:"auto",opacity:"1"})},6000)}
$(document).ready(()=>{var video=$("#intro").get(0);var music=document.getElementById("music");video.volume=0.05;music.volume=0.1;$("#volUp").click(()=>{if(music.volume!=1){music.volume+=0.1;}});$("#volDown").click(()=>{if(music.volume!=0){music.volume-=0.1;}})
$("#button").click(()=>{$("#button").fadeOut(500);video.play();});$(".pip").click(function(){var opens=$(this).attr("opens");console.log("Pip clicked!");$(".pip").removeClass("selected");$(this).addClass("selected");$(".tab").fadeOut(200);setTimeout(function(){$(opens).fadeIn(200);},200)})
$(".friend, .image, .skill .logo").each(function(){var image=$(this).attr("img");if(!image){image="https://4.bp.blogspot.com/-YZ3S5BXNVO8/Wo3Uu1OBlkI/AAAAAAAA5fI/35MlKNhZG6sNyd1ZTipTbhPUZ4Qsg_VRgCEwYBhgL/s1600/3369.jpg";}
$(this).css("background-image",`url(${image})`);});$(".friend").click(function(){var face=$(this).attr("img");var name=$(this).attr("name");var desc=$(this).attr("desc");var link=$(this).attr("profile");if(!face){face="https://4.bp.blogspot.com/-YZ3S5BXNVO8/Wo3Uu1OBlkI/AAAAAAAA5fI/35MlKNhZG6sNyd1ZTipTbhPUZ4Qsg_VRgCEwYBhgL/s1600/3369.jpg";}
if(!name){name="Coming Soon!"}
if(!desc){desc="";}
$("#friendCard #face").css("background-image",`url(${face})`);$("#friendCard #name").html(name);$("#friendCard #desc").html(desc);$("#friendCard .profile a").attr("href",link);$("#friendCard").css({transform:"translate(-50%, -50%)",opacity:'1',pointerEvents:"all"});});$("#friendCard #exit").click(()=>{$("#friendCard").css({transform:"translate(-50%, -150%)",opacity:"0",pointerEvents:"none"})})
var totalImages=$("#gallery .image").length;var currentOpenIndex;$(".image").click(function(){var image=$(this).attr("img");currentOpenIndex=$(this).index();console.log(currentOpenIndex);$("#gallOverlay #picture img").attr("src",image);$("#gallOverlay").fadeIn(500);});$("#gallOverlay #prev").click(()=>{console.log("back")
var image;$("#gallOverlay #picture img").attr("src","https://upload.wikimedia.org/wikipedia/commons/3/3a/Gray_circles_rotate.gif")
if(currentOpenIndex==0){currentOpenIndex=totalImages-1;}else{currentOpenIndex=currentOpenIndex-1;};console.log(currentOpenIndex);image=$("#gallery .image").eq(currentOpenIndex).attr("img");$("#gallOverlay #picture img").attr("src",image)});$("#gallOverlay #next").click(()=>{console.log("next!")
$("#gallOverlay #picture img").attr("src","https://upload.wikimedia.org/wikipedia/commons/3/3a/Gray_circles_rotate.gif")
var image;if(currentOpenIndex==totalImages-1){currentOpenIndex=0;}else{currentOpenIndex=currentOpenIndex+1;};console.log(currentOpenIndex);image=$("#gallery .image").eq(currentOpenIndex).attr("img");$("#gallOverlay #picture img").attr("src",image)});$("#gallOverlay #picture").click(()=>{$("#gallOverlay").fadeOut(200);});})