$(document).ready(()=>{$("body").sakura({minSize:14,maxSize:19});var lag=2,tranLag=0,music=document.getElementById("music");music.volume=0.1;currentVolume=10;var playing,loaded,curIndex,images=$(".gallImage").length;function checkLoad(){if(music.readyState===4){console.log("Finally loaded.");loaded=true;setTimeout(function(){playing=!music.paused;console.log(playing);addMusic();setTimeout(function(){volumeButtons(playing);},100);},600);}else if(!loaded){console.log("Nope. Not yet.");setTimeout(checkLoad,100);};}
function addMusic(){$("body").append($("<button />",{class:`music`}))}
function showToast(text){var newToast=document.createElement("div");newToast.classList.add("toast");newToast.innerHTML=text;document.body.appendChild(newToast);setTimeout(function(){newToast.parentNode.removeChild(newToast);},3000);}
function volumeButtons(state){$("<div />",{class:`icon ${state?"pause":"play"}`,click:function(){if(playing){music.pause();playing=false;$(this).removeClass("pause");$(this).addClass("play");}else{music.play();playing=true;$(this).removeClass("play");$(this).addClass("pause");}}}).appendTo("button.music");$("<div />",{class:"vol",html:"+",click:function(){console.log(music.volume);if(currentVolume==100){showToast("Max volume hit!")
return;}else{currentVolume+=10;music.volume=currentVolume/100;}}}).appendTo("button.music");$("<div />",{class:"vol",html:"-",click:function(){console.log(music.volume);if(currentVolume==0){showToast("Music is already muted.")
return;}else{currentVolume-=10;music.volume=currentVolume/100;}}}).appendTo("button.music");}
checkLoad();$(".button").each(function(){$(this).css("animation-delay",`${lag}s`);$(this).css("transition-delay",`${tranLag}s`)
$(this).append($("<img>",{src:$(this).attr("img")}));$(this).removeAttr("img");lag+=.5;tranLag+=.5;});$(".friend, .gallImage").each(function(){var img=$(this).attr("img");if(!img){img="https://media1.giphy.com/media/mQan4KV9MNoJy/giphy.gif";};if($(this).hasClass("friend")){if(!$(this).attr("target")){$(this).attr("target","_blank");}}
$(this).css("background-image",`url(${img})`);});$("body").append($("<div />",{id:"name",html:"My name is<br><span>Satomi Hana</span>"}));$("body").append($("<div />",{id:"tooltips"}));setTimeout(function(){$("#name").fadeOut(1500);setTimeout(function(){$("#name").remove();},1500)},4000);setTimeout(function(){$(".button").addClass("animate");setTimeout(function(){$("#ooc").addClass("appearFirst");$(".button").css("transition-delay","0s");$(".button").css("transition-duration",".2s");},1500);},5500);$(".button").mouseenter(function(){var tipPosition=$(this).offset();var height=$(this).outerHeight();var width=$(this).outerWidth();$("#tooltips").append($("<div />",{class:`tooltip bottom`,style:`top:${tipPosition.top+height}px;left:${tipPosition.left+width/2}px`,html:$(this).attr("tab")}));});$(".friend").mouseenter(function(){var tipPosition=$(this).offset();var height=$(this).outerHeight();var width=$(this).outerWidth();if($(this).find(".desc")[0]){$("#tooltips").append($("<div />",{class:"tooltip right",style:`top:${tipPosition.top+height/2}px;left:${tipPosition.left+width}px`,html:$(this).find(".desc").html()}));}else{console.log("No description. No tooltip");}});$(".button, .friend").mouseleave(function(){var tooltip=document.getElementsByClassName("tooltip");if(tooltip.length>0){$(".tooltip").remove();}});$(".button").click(function(){var opens=$(this).attr("opens");$(".button").removeClass("selected");$(this).addClass("selected");$(".box").removeClass("appear appearFirst")
$(opens).addClass("appear");});function changePicture(ind){var newPic=$(".gallImage").eq(ind).attr("img");if(!newPic){showToast("Image unavailable. Click again to skip to next picture.");}
$("#gallOverlay img").attr("src",`${newPic}`);}
$(".gallImage").click(function(){console.log("clicked!");curIndex=$(this).index();var showImage=$(this).attr("img");if(!showImage){showToast("Image unavailable");return;}
$("<div />",{id:"gallOverlay"}).insertBefore("#tooltips");$("<div />",{class:"flexBox"}).appendTo("#gallOverlay");$("<div />",{id:"gallExit",click:function(){$("#gallOverlay").fadeOut(200);setTimeout(function(){$("#gallOverlay").remove();},200);}}).appendTo("#gallOverlay .flexBox")
$("<div />",{class:"prev",click:function(){if(curIndex!==0){--curIndex;changePicture(curIndex)}else{curIndex=images-1;changePicture(curIndex)}}}).appendTo("#gallOverlay .flexBox");$("<img>",{src:$(this).attr("img")}).appendTo("#gallOverlay .flexBox");$("<div />",{class:"next",click:function(){if(curIndex!==(images-1)){++curIndex;changePicture(curIndex)}else{curIndex=0;changePicture(curIndex)}}}).appendTo("#gallOverlay .flexBox");});})