$(document).ready(()=>{function tooltip(){var title=$(this).attr("title");$(this).removeAttr("title");this.TooltipMessage=$("<div/>",{class:"tooltipMessage",style:"display: none;"});this.TooltipMessage.html("<span>"+title+"</span>");$("body").append(this.TooltipMessage);if($(this).hasClass("tooltipLeft")){this.TooltipMessage.addClass("left");}
$(this).hover(tooltipFadeIn,tooltipFadeOut);$(this).mousemove(tooltipMousemove);}
function tooltipFadeIn(){this.TooltipMessage.stop(true,false).fadeIn();}
function tooltipFadeOut(){this.TooltipMessage.stop(true,false).fadeOut();}
function tooltipMousemove(e){var offset={left:e.pageX,top:e.pageY+25};if(this.TooltipMessage.hasClass("left")){offset.left-=this.TooltipMessage.width()+20;}else{offset.left-=130;}
this.TooltipMessage.offset(offset);}
$(function(e){$(".tooltip").each(tooltip);});$('.header').attr('x','0');$('.header').attr('y','2vw');$('.bold').attr('x','0');$('.bold').attr('y','1vw');$('.bullet').attr('x','0');$('.bullet').attr('y','1vw');$('#miniscrap').attr('title','The book pulses with a strange white light.')
$('#clickme').attr('title','The book pulses with a strange white light.')
$('#arrowright').click(()=>{$('#scene1').toggle("slide",{direction:'left'});$('#scene2').toggle("slide",{direction:'right'});});$('#arrowleft').click(()=>{$('#scene2').toggle("slide",{direction:'right'});$('#scene1').toggle("slide",{direction:'left'})})
$('#miniscrap').click(()=>{$('#actualscrapbook').fadeIn('slow','swing');$('#xmark').fadeIn('slow','swing');$('#miniscrap').fadeOut('slow','swing');})
$('#clickme').click(()=>{$('#actualscrapbook').fadeIn('slow','swing');$('#xmark').fadeIn('slow','swing');$('#miniscrap').fadeOut('slow','swing');$('#clickme').fadeOut('slow','swing');})
$(document).mousedown(()=>{if(event.which==3){$('#warning').show();}})
$.ajax({url:"https://rawgit.com/EllexideCodes/Profile-Codes/master/red/clock.txt",dataType:'text',success:function(data){$('#clock').html(data);(function(){'use strict';let seconds=document.getElementById('second_time'),munutes=document.getElementById('minute_time'),hours=document.getElementById('hour_time'),s,m,h,S,M,H,time;function windup(){time=new Date(),s=time.getSeconds(),m=time.getMinutes(),h=time.getHours(),S=s*6,M=m*6+s/10,H=h*30+0.5*m;seconds.style.transform='rotate('+S+'deg)';munutes.style.transform='rotate('+M+'deg)';hours.style.transform='rotate('+H+'deg)';console.log('windup: '+h+':'+m+':'+s);tick.volume=chime.volume=1;}
setTimeout(windup,0);let vis=(function(){let stateKey,eventKey,keys={hidden:'visibilitychange',webkitHidden:'webkitvisibilitychange',mozHidden:'mozvisibilitychange',msHidden:'msvisibilitychange'};for(stateKey in keys){if(stateKey in document){eventKey=keys[stateKey];break;}}
return function(c){if(c)document.addEventListener(eventKey,c);return!document[stateKey];}})();vis(function(){if(vis()){setTimeout(function(){windup();console.log('tab is visible - has focus');},300);}else{console.log('tab is invisible - has blur');tick.volume=chime.volume=0.1;}});let notIE=(document.documentMode===undefined),isChromium=window.chrome;if(notIE&&!isChromium){$(window).on('focusin',function(){setTimeout(function(){windup();console.log('focus');},300);}).on('focusout',function(){console.log('blur');tick.volume=chime.volume=0.1;});}else{if(window.addEventListener){window.addEventListener('focus',function(event){setTimeout(function(){windup();console.log('focus');},300);},false);window.addEventListener('blur',function(event){console.log('blur');tick.volume=chime.volume=0.1;},false);}else{window.attachEvent('focus',function(event){setTimeout(function(){windup();console.log('focus');},300);});window.attachEvent('blur',function(event){console.log('blur');tick.volume=chime.volume=0.1;});}}
const tick=document.getElementById('tick');const chime=document.getElementById('chime');const sound_dir='http://www.gerasimenko.com/sandbox/codepen/sounds/';let bell,tock='tock.wav';tick.src=sound_dir+tock;function hourly_chime(n){console.log('plays left: '+n);if(n===0){return;}else{chime.pause();chime.currentTime=0;chime.play();n--;setTimeout(function(){hourly_chime(n);},3000);}}
setInterval(function(){time=new Date(),s=time.getSeconds(),m=time.getMinutes(),h=time.getHours();console.log('watch: '+h+':'+m+':'+s);tick.play();if(s===0&&(m===15||m===30||m===45)){bell='ding-tone.wav';chime.src=sound_dir+bell;hourly_chime(m/15);}else if(s===0&&m===0){bell='bell-japanese.wav';chime.src=sound_dir+bell;h>12?h=h-12:h;hourly_chime(h);}},1000);})();},error:function(){console.log('Well you\'re pretty much fucked.')}})
$.ajax({url:'https://rawgit.com/EllexideCodes/Profile-Codes/master/red/pop%20up%20warning.txt',dataType:'text',success:function(data){$('#warning').html(data);}})
$('#book').turn({acceleration:true,pages:numberOfPages,elevation:45,gradients:!$.isTouch,when:{turning:function(e,page,view){var range=$(this).turn('range',page);for(page=range[0];page<=range[1];page++)
addPage(page,$(this));},turned:function(e,page){$('#page-number').val(page);}}});$('#clickme').click(()=>{$('#clickme').removeClass('bookPulse');$('#miniscrap').addClass('bookPulse');$('#scrapbook').turn({acceleration:true,pages:numberOfPictures,elevation:45,gradients:!$.isTouch,when:{turning:function(e,page,view){var range=$(this).turn('range',page);for(page=range[0];page<=range[1];page++)
addPic(page,$(this));},turned:function(e,page){$('#page-number').val(page);}}});});})
